version: "3"

services: 
  traefik:
    image: traefik:alpine
    ports: 
      - 80:80
      - 443:443
      - 8080:8080
    volumes: 
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: emilevauge/whoami
    labels: 
      - traefik.enable=true
      - "traefik.frontend.rule=Host:whoami.liangyouapp.com"