defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.api]
  address = ":8080"

[api]
entryPoint = "api"

[acme]
email = "510830568@qq.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "liangyouapp.com"
  sans = ["whoami.liangyouapp.com"]


[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "liangyouapp.com"
exposedByDefault = false
# swarmmode=true
